name: Docker Build Matrix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened] # trigger on PRs
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test Docker Image
    runs-on:
      group: aws-g6-12xlarge-plus
    permissions:
      contents: read
      packages: write
    strategy:
      max-parallel: 2
      matrix:
        python: [
            "3.10",
            # avoid for debugging
            # "3.11", "3.12"
          ]
        ubuntu: ["18.04", "20.04", "22.04"]
        cuda: ["11.8.0", "12.1.0", "12.2.0", "12.4.0", "12.6.0"]
        torch: ["2.4.0", "2.5.0"]
        exclude:
          # exclude cuda 12+ for ubuntu 18.04
          - ubuntu: "18.04"
            cuda: "12.1.0"
          - ubuntu: "18.04"
            cuda: "12.2.0"
          - ubuntu: "18.04"
            cuda: "12.4.0"
          - ubuntu: "18.04"
            cuda: "12.6.0"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/hf_kernels
          tags: |
            type=raw,value=${{ matrix.cuda }}-${{ matrix.torch }}-python${{ matrix.python }}-ubuntu${{ matrix.ubuntu }}
            type=sha,prefix=${{ matrix.cuda }}-${{ matrix.torch }}-python${{ matrix.python }}-ubuntu${{ matrix.ubuntu }}-

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          build-args: |
            PYTHON_VERSION=${{ matrix.python }}
            UBUNTU_VERSION=${{ matrix.ubuntu }}
            CUDA_VERSION=${{ matrix.cuda }}
            TORCH_VERSION=${{ matrix.torch }}
          push: false
          load: true # attempt loading directly to the runner
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Save image name for testing
        run: |
          echo "${{ steps.meta.outputs.tags }}" | head -n 1 >> $GITHUB_WORKSPACE/image_tags.txt

  test:
    needs: build
    name: Test Docker Images
    runs-on:
      group: aws-g6-12xlarge-plus
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Tests for all images
        run: |
          # Read all image tags and test each one
          while IFS= read -r IMAGE_ID; do
            echo "Testing image: $IMAGE_ID"
            docker run --gpus all \
              -v ${{ github.workspace }}/tests:/workspace/tests \
              ${IMAGE_ID}
          done < $GITHUB_WORKSPACE/image_tags.txt